#!/usr/bin/env python3
# worklog.py - Shared work-item store for agent-to-agent coordination.
#
# Personas in this harness NEVER pass task context or results directly to each
# other. They coordinate exclusively through shared state: a requester writes a
# "work item" here, invokes the worker with only a pointer ("please work on
# <id>"), the worker reads the item, does the work, and writes its findings back
# here. This script is that shared state.
#
# The backend is pluggable (env WORKLOG_BACKEND):
#   - "local" (default): one JSON file per work item under WORKLOG_DIR
#     (default /opt/data/worklog/), on the PVC both personas share.
#   - "github": a documented seam (GitHubIssueBackend) to back work items with
#     GitHub issues/PRs via the existing Minty token broker. Not yet implemented.
#
# Because the interface is backend-agnostic, the agents' coordination protocol
# is identical regardless of where the shared state actually lives.

import argparse
import json
import os
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

VALID_STATUSES = ("open", "in_progress", "blocked", "done", "cancelled")


def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _read_arg(inline: str | None, path: str | None) -> str | None:
    """Resolve a text value from --X, --X-file <path>, or '-' (stdin)."""
    if path:
        if path == "-":
            return sys.stdin.read()
        return Path(path).read_text(encoding="utf-8")
    return inline


class WorkItemBackend:
    """Abstract shared-state backend."""

    def create(self, item: dict) -> str:  # returns work item id
        raise NotImplementedError

    def get(self, item_id: str) -> dict:
        raise NotImplementedError

    def save(self, item: dict) -> None:
        raise NotImplementedError

    def list(self) -> list[dict]:
        raise NotImplementedError


class LocalFileBackend(WorkItemBackend):
    """Stores each work item as a JSON file under WORKLOG_DIR (on the shared PVC)."""

    def __init__(self, base_dir: Path) -> None:
        self.base_dir = base_dir
        self.base_dir.mkdir(parents=True, exist_ok=True)

    def _path(self, item_id: str) -> Path:
        # item_id is generated by us (wi-<hex>); keep it filesystem-safe.
        if not item_id or "/" in item_id or ".." in item_id:
            raise SystemExit(f"ERROR: invalid work item id: {item_id!r}")
        return self.base_dir / f"{item_id}.json"

    def create(self, item: dict) -> str:
        item_id = item["id"]
        path = self._path(item_id)
        if path.exists():
            raise SystemExit(f"ERROR: work item already exists: {item_id}")
        path.write_text(json.dumps(item, indent=2), encoding="utf-8")
        return item_id

    def get(self, item_id: str) -> dict:
        path = self._path(item_id)
        if not path.exists():
            raise SystemExit(f"ERROR: work item not found: {item_id}")
        return json.loads(path.read_text(encoding="utf-8"))

    def save(self, item: dict) -> None:
        self._path(item["id"]).write_text(json.dumps(item, indent=2), encoding="utf-8")

    def list(self) -> list[dict]:
        items = []
        for p in sorted(self.base_dir.glob("*.json")):
            try:
                items.append(json.loads(p.read_text(encoding="utf-8")))
            except Exception:  # noqa: BLE001 - skip corrupt entries
                continue
        return items


class GitHubIssueBackend(WorkItemBackend):
    """Seam for backing work items with GitHub issues/PRs via the Minty token broker.

    Not implemented in this MVP. The intended mapping:
      - create() opens a GitHub issue (title=request title, body=request).
      - get()/save() read/append issue comments for request, findings, patch.
      - status maps to issue state / labels.
    Implement against the same interface so the agent protocol is unchanged.
    """

    def __init__(self, *_args, **_kwargs) -> None:
        raise SystemExit(
            "ERROR: WORKLOG_BACKEND=github is a documented seam and is not implemented yet. "
            "Use the default local-file backend (unset WORKLOG_BACKEND or set it to 'local')."
        )


def get_backend() -> WorkItemBackend:
    backend = os.environ.get("WORKLOG_BACKEND", "local").lower()
    if backend == "local":
        return LocalFileBackend(Path(os.environ.get("WORKLOG_DIR", "/opt/data/worklog")))
    if backend == "github":
        return GitHubIssueBackend()
    raise SystemExit(f"ERROR: unknown WORKLOG_BACKEND: {backend!r} (expected 'local' or 'github').")


def _append_log(item: dict, author: str, message: str) -> None:
    item.setdefault("log", []).append({"at": _utc_now(), "author": author, "message": message})
    item["updated_at"] = _utc_now()


def render_markdown(item: dict) -> str:
    lines = [
        f"# Work Item {item['id']}: {item.get('title', '(untitled)')}",
        "",
        f"- **status:** {item.get('status', '?')}",
        f"- **requester:** {item.get('requester', '?')}",
        f"- **assignee:** {item.get('assignee', '?')}",
    ]
    target = item.get("target") or {}
    if target:
        lines.append(
            f"- **target cluster:** {target.get('project', '?')}/{target.get('cluster', '?')}/{target.get('location', '?')}"
        )
    lines += [
        f"- **created_at:** {item.get('created_at', '?')}",
        f"- **updated_at:** {item.get('updated_at', '?')}",
        "",
        "## Request",
        "",
        item.get("request") or "_(none)_",
        "",
        "## Findings",
        "",
        item.get("findings") or "_(none yet)_",
        "",
        "## Proposed Patch",
        "",
        item.get("patch") or "_(none)_",
        "",
        "## Log",
        "",
    ]
    for entry in item.get("log", []):
        lines.append(f"- `{entry['at']}` **{entry['author']}**: {entry['message']}")
    return "\n".join(lines) + "\n"


def cmd_create(args: argparse.Namespace) -> None:
    backend = get_backend()
    request = _read_arg(args.request, args.request_file)
    item = {
        "id": f"wi-{uuid.uuid4().hex[:8]}",
        "title": args.title,
        "status": "open",
        "requester": args.requester,
        "assignee": args.assignee,
        "request": request,
        "findings": None,
        "patch": None,
        "created_at": _utc_now(),
        "updated_at": _utc_now(),
        "log": [],
    }
    if args.project or args.cluster or args.location:
        item["target"] = {"project": args.project, "cluster": args.cluster, "location": args.location}
    _append_log(item, args.requester, f"created and assigned to {args.assignee}")
    print(backend.create(item))


def cmd_show(args: argparse.Namespace) -> None:
    item = get_backend().get(args.id)
    if args.json:
        print(json.dumps(item, indent=2))
    else:
        sys.stdout.write(render_markdown(item))


def cmd_update(args: argparse.Namespace) -> None:
    backend = get_backend()
    item = backend.get(args.id)
    changed = []
    if args.status:
        if args.status not in VALID_STATUSES:
            raise SystemExit(f"ERROR: invalid status {args.status!r}; expected one of {', '.join(VALID_STATUSES)}.")
        item["status"] = args.status
        changed.append(f"status={args.status}")
    findings = _read_arg(args.findings, args.findings_file)
    if findings is not None:
        item["findings"] = findings
        changed.append("findings")
    patch = _read_arg(args.patch, args.patch_file)
    if patch is not None:
        item["patch"] = patch
        changed.append("patch")
    author = args.author or item.get("assignee") or "unknown"
    note = args.note or (f"updated {', '.join(changed)}" if changed else "touched")
    _append_log(item, author, note)
    backend.save(item)
    print(args.id)


def cmd_list(args: argparse.Namespace) -> None:
    for item in get_backend().list():
        if args.status and item.get("status") != args.status:
            continue
        if args.assignee and item.get("assignee") != args.assignee:
            continue
        print(f"{item['id']}\t{item.get('status', '?')}\t{item.get('assignee', '?')}\t{item.get('title', '')}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Shared work-item store for agent-to-agent coordination.")
    sub = parser.add_subparsers(dest="command", required=True)

    sp = sub.add_parser("create", help="Create a work item and print its id")
    sp.add_argument("--title", required=True)
    sp.add_argument("--requester", required=True, help="Persona creating the item (e.g. platform)")
    sp.add_argument("--assignee", required=True, help="Persona expected to work it (e.g. cluster)")
    sp.add_argument("--request")
    sp.add_argument("--request-file", dest="request_file", help="Path to request body, or '-' for stdin")
    sp.add_argument("--project")
    sp.add_argument("--cluster")
    sp.add_argument("--location")

    sp = sub.add_parser("show", help="Render a work item")
    sp.add_argument("id")
    sp.add_argument("--json", action="store_true")

    sp = sub.add_parser("update", help="Update a work item's status/findings/patch")
    sp.add_argument("id")
    sp.add_argument("--status")
    sp.add_argument("--findings")
    sp.add_argument("--findings-file", dest="findings_file", help="Path to findings, or '-' for stdin")
    sp.add_argument("--patch")
    sp.add_argument("--patch-file", dest="patch_file", help="Path to proposed patch, or '-' for stdin")
    sp.add_argument("--note")
    sp.add_argument("--author")

    sp = sub.add_parser("list", help="List work items")
    sp.add_argument("--status")
    sp.add_argument("--assignee")

    args = parser.parse_args()
    {"create": cmd_create, "show": cmd_show, "update": cmd_update, "list": cmd_list}[args.command](args)


if __name__ == "__main__":
    main()
